FROM python:3.7-slim-stretch

RUN apt-get update && \
        apt-get -y install libglib2.0-0 git binutils --no-install-recommends && \
        pip install pyinstaller \
        rm -rf /var/lib/apt/lists/* 

